# -*- coding: utf-8 -*-
"""codigo_para_cargar_bd

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sh0ffQaUwwcuLPaSSNmIstLfqjU-2TfF
"""

import pandas as pd

bd = pd.read_csv("/content/drive/MyDrive/csvs/lagrimas_ghibli.csv", sep=",")

display(bd)

import os

# List files in your Google Drive
# Adjust the path below if you know the file is in a specific subfolder
for root, dirs, files in os.walk("/content/drive/MyDrive/"):
    for file in files:
        if "lagrimas_ghibli.csv" in file:
            print(os.path.join(root, file))